name: ci-cd-pipeline-prod
on:
    push:
        branches:
            - dev
            - stage
            - prod

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: set up node
              uses: actions/setup-node@v3
              with:
                node-version: '22'
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm test

    deploy-dev:
        needs: build
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: dev
    
    deploy-stage:
        needs: deploy-dev
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: stage

    deploy-prod:
        needs: deploy-stage
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: prod