name: ci-cd-pipeline-dev
on:
    push:
        branches:
            - dev
            - stage
            - prod

    workflow_dispatch:

    repository_dispatch:
        types: [deploy-dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: set up node
              uses: actions/setup-node@v3
              with:
                node-version: '22'
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm test

    deploy-dev:
        needs: build
        if: github.ref == 'refs/heads/dev'
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: dev
    
    deploy-stage:
        needs: build
        if: github.ref == 'refs/heads/stage'
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: stage

    deploy-prod:
        needs: build
        if: github.ref == 'refs/heads/prod'
        uses: ./.github/workflows/reusable-workflow-deploy.yml
        with:
            environment: prod
