name: Reusable Deploy Workflow

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: ${{ inputs.environment }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.environment }}"